module formatos_numericos;

localparam LARGURA_INTEIRO = 8;

localparam BITS_INTEIROS_PONTO_FIXO = 3;
localparam BITS_FRACIONARIOS_PONTO_FIXO = 5;
localparam LARGURA_TOTAL_PONTO_FIXO = BITS_INTEIROS_PONTO_FIXO + BITS_FRACIONARIOS_PONTO_FIXO;

localparam LARGURA_SINAL_PONTO_FLUTUANTE = 1;
localparam LARGURA_EXPOENTE_PONTO_FLUTUANTE = 4;
localparam LARGURA_MANTISSA_PONTO_FLUTUANTE = 11;
localparam LARGURA_TOTAL_PONTO_FLUTUANTE = LARGURA_SINAL_PONTO_FLUTUANTE + LARGURA_EXPOENTE_PONTO_FLUTUANTE + LARGURA_MANTISSA_PONTO_FLUTUANTE;

endmodule